
platform :ios,'9.0'
pod "AFNetworking","3.0.2"
pod 'FrameAccessor', '1.3.2'
pod 'TMCache', '2.1.0'
pod 'SDWebImage', '3.7.3'
pod 'ReactiveCocoa','2.5'
pod 'UIColor-Utilities','1.0.1'
pod 'Masonry','0.6.2'
pod 'MJExtension'
pod 'AMap2DMap', '~> 3.3.0'
pod 'AMapSearch', '~> 3.3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'
pod 'pop'
